name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.3.2
  meta: 1.9.1
  dart_jsonwebtoken: ^2.11.0
  datetime_picker_formfield_new: 2.1.0
  intl_phone_number_input: 0.7.3+1 
  intl: ^0.18.1
  image_picker: 1.0.4
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    
